### ISSUE TITLE
找不到 flask_mongoengine

### ISSUE THREAD

**Issue by wapscccs** [yuzhanglong/EasyQuestionnaire-backend#1]
用宝塔面板搭建，提示找不到 flask_mongoengine
请教下如何解决，感谢

**Comment by yuzhanglong** [comment]
试着用pip原生的镜像源安装 国内的镜像源貌似装不上（我在克隆这个项目的时候也遇到类似问题 ）

**Comment by wapscccs** [comment]
> 试着用pip原生的补充源安装国内的过多源貌似装不上（我在克隆这个项目的时候也遇到类似问题）

好的，谢谢，那我现在本地配置一下

**Comment by yuzhanglong** [comment]
> > 试着用pip原生的补充源安装国内的过多源貌似装不上（我在克隆这个项目的时候也遇到类似问题）
> 
> 好的，谢谢，那我现在本地配置一下

hi,我最近准备重构这个项目，对于你上次提到了**flaskmongoengine**安装的问题，我当时的建议是使用**原生镜像源** 有时使用国内的清华大学镜像源是无法安装的（当时使用python3.7版本），最近我找出来了一个还行的办法（至少不用手动再输入额外的命令了）：先为虚拟环境安装一个名叫wheel的包（你可以把这个包名称放到requirements.txt里面），就能顺利安装上flaskmongoengine。

如果以后装别的包安装出现问题，也可以试试上面这个方法，说不定能奏效😄
